### ISSUE TITLE
Option to Have Roll Use Stamina Only Instead on Relying on Roll Cooldown?

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/combatroll-extension#1]
Rolling based on the amount of stamina a player has instead of waiting for the cooldown to complete could be a neat option to make rolling more dynamic (assuming that I configured the stamina cost to be risky enough for the player to not spam rolls all the time xd).

**Comment by TheRedBrain** [comment]
that's already possible! :)

go to config/combatroll/server.json
set "roll_cooldown" to 0.0

to optionally remove every influence the hunger system has over the roll mechanic set
"exhaust_on_roll" to 0.0 
and
"food_level_required" to 0.0


optionally removing the HUD icon indicating the roll cooldown:
go to the config/combatroll/hud_config.json and set
"origin" to "BOTTOM"
"field_1343" to 100.0
"field_1342" to 0.0


optionally removing the cooldown sound:
go to the config/combatroll/client.json and set
"playCooldownSound" to false

**Comment by InputandOutput** [comment]
Guh, count this to the list of "things that I've suggested that are already implemented".

**Comment by InputandOutput** [comment]
Closing.
