### ISSUE TITLE
1.20 version

### ISSUE THREAD

**Issue by heide-oficial** [TheRedBrain/combatroll-extension#3]
Any chance we can get a 1.20 version? A lot of mods that I enjoy are only available for 1.20, so I can't use this mod :(

**Comment by TheRedBrain** [comment]
Hi

Versions 1.0.0 and 1.1.0 are both for 1.20.1

If you are talking about 1.20.0, I'm sorry, but I won't backport my mods. I would rather spend my limited modding time on supporting the newest Minecraft versions/ new content.

**Comment by heide-oficial** [comment]
I know that fell. Thanks for the reply!
