### ISSUE TITLE
Suggestion: Option for disabling the original mod's rolling cooldown. 

### ISSUE THREAD

**Issue by CaesarSP** [TheRedBrain/combatroll-extension#4]
The title. Without an option like that, this mod feels redundant.

**Comment by TheRedBrain** [comment]
Hi!

Combat Roll itself has a config option for that already!

Location of config:
config/combatroll/server.json5

change the line
"roll_cooldown": 4.0,
to
"roll_cooldown": 0.0,

and restart the game/server
